# Generated by Django 5.1.7 on 2025-03-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_response_responsedetail_delete_surveyresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='is_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionset',
            name='survey_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
