# Generated by Django 5.1.7 on 2025-03-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_questionset_is_today_questionset_survey_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='codes_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionset',
            name='set_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
