# Generated by Django 5.1.7 on 2025-03-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_questionset_codes_json_questionset_set_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsedetail',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
    ]
