# Generated by Django 5.1.7 on 2025-03-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_responsedetail_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='etc_opinion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='panel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
